# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Vue Web App

on:
  push:
    branches:
      - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureStaticWebApp@0
    inputs:
      app_location: "./" 
      api_location: "api"
      output_location: "dist"
    env:
      azure_static_web_apps_api_token: ${{secrets.AZURE_WEB_TOKEN}}

# File: .github/workflows/workflow.yml
# name: JavaScript CI

# on:
#   push:
#     branches:
#       - master

# env:
#   AZURE_WEBAPP_NAME: paadm-web   # set this to your application's name
#   AZURE_WEBAPP_PACKAGE_PATH: './'      # set this to the path to your web app project, defaults to the repository root
#   NODE_VERSION: '14.x'                # set this to the node version to use

# jobs:
#   build-and-deploy:
#     name: Build and Deploy
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@main
#     - name: Use Node.js ${{ env.NODE_VERSION }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ env.NODE_VERSION }}
#     - name: npm install, build, and test
#       run: |
#         # Build and test the project, then
#         # deploy to Azure Web App.
#         npm install
#         npm run build --if-present
#         npm run test --if-present
#       working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
#     - name: 'Deploy to Azure WebApp'
#       uses: AzureStaticWebApp@0
#       with: 
#         app-name: ${{ env.AZURE_WEBAPP_NAME }}
#         # publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#         publish-profile: ${{ secrets.AZURE_WEB_TOKEN }}
#         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}dist
      
# name: deploy
# on:
#   push:
#     branches:
#       - master
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - uses: actions/setup-node@v1
#         with:
#           node-version: "14"
#       - name: setup git auth
#         env:
#           email: "deraldosp@gmail.com"
#           username: "${{secrets.USERNAME}}"
#           access_token: "${{secrets.ACCESS_TOKEN}}"
#         run: |
#           git config --global credential.helper store
#           echo "https://${{secrets.ACCESS_TOKEN}}:x-oauth-basic@github.com" > ~/.git-credentials
#           git config --global user.email $email
#           git config --global user.name $username
#       - name: deploy to pa-page
#         run: |
#           npm i
#           NODE_ENV=production npm run build
#           cd dist
#           git init
#           git add -A
#           git commit -m "🚀 Deploy id ${GITHUB_RUN_ID}"
#           git push -f "https://github.com/deraldosp/paroquialadm-frontend.git" master:gh-pages
